# docker build --no-cache=true -t qchs-2018 -f DockerFile .

FROM tensorflow/tensorflow:1.8.0-py3

RUN mkdir -p /tmp/setup && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        libxpm4 \
        libtbb2 \
        tar \
        wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --trusted-host pypi.python.org matplotlib==2.1.2 pandas==0.22.0 six numpy==1.14.0 seaborn==0.8.1 jupyter scikit-learn==0.19.1 tensorflow==1.8.0 keras==2.1.6

RUN cd /usr/local && \
    git clone https://github.com/GilesStrong/QCHS-2018 /QCHS-2018 && \
    cd /QCHS-2018 && \
    mkdir Data && \
    wget -O Data/atlas-higgs-challenge-2014-v2.csv.gz http://opendata.cern.ch/record/328/files/atlas-higgs-challenge-2014-v2.csv.gz && \
	gunzip Data/atlas-higgs-challenge-2014-v2.csv.gz && \
    python Modules/Data_Import.py

WORKDIR /QCHS-2018

ADD . /QCHS-2018

ENV KERAS_BACKEND tensorflow

EXPOSE 8888

CMD ["/run_jupyter.sh", "--allow-root"]