name: QCHS-2018
channels:
  - conda-forge
  - defaults
dependencies:
  - six
  - jupyter
  - pip
  - pip:
    - matplotlib==2.1.2
    - pandas==0.22.0
    - numpy==1.14.0
    - seaborn==0.8.1
    - scikit-learn==0.19.1
    - tensorflow==1.8.0
    - keras==2.1.6
    - statsmodels==0.8.0